# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14syiVSwyJuLhXC0jZQUQT9CpSImvEMoq
"""

import pandas as pd
df = pd.DataFrame ({ 'Ism': ['Zuloyho', 'Nigora','Sarvinoz','Oybek','Ogabek','Oyatbek','Elyor','Bekzod','Rahimjon','Ali'],
                   'Familiya': ['Qadamova','Yusupova','Toxirova','Akramov','Malikov','Qodirov','Valijonov','Karimov','Inomov','Solijonov'],
                   'Yoshi': ['19','20','19','19','19','19','19','19','19','19'],
                   'Kursi': ['2','2','2','2','2','2','2','2','2','2']
                   })
print(df)